version: "3.9"

services:  
  mariadb:
    image: mariadb 
    volumes:
      - mariaSQL_01:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    
  adminer:
    image: adminer:latest
    restart: always
    # remove comments if you need to access adminer via port; could be removed entire; possible port conflict with frontend
    ports:
      - 8081:8080

  node:
    build: './server' 
    restart: always
    #For production it should not ne necessary to expose ports; containers should be able to use internal network directly
    ports:
      - 4001:4001
    volumes:
      - .images:/images
      - ./server/src/controllers:/app/src/controllers
      - ./server/src/dblogic:/app/src/dblogic
     

  vue:
    build: './frontend'
    restart: always
    ports:
      - 8080:8080
    
  

volumes:
  mariaSQL_01:
    external: true
  images:
    external: true
