version: "3.9"

services:  
  mariadb:
    image: mariadb:latest
    deploy:
        replicas: 3
    volumes:
      - /mount/database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    
  adminer:
    image: adminer:latest
    deploy:
      replicas: 1
    restart: always
    # remove comments if you need to access adminer via port; could be removed entire; possible port conflict with frontend
    ports:
      - 8081:8080

  node:
    image: node:16.4.2-alpine3.11
    build: 
      context: './server'
      dockerfile: Dockerfile
    deploy:
      replicas: 3 
    restart: always
    #For production it should not ne necessary to expose ports; containers should be able to use internal network directly
    ports:
      - 4001:4001
    volumes:
      - /mount/images:/images
      - ./server/src/controllers:/app/src/controllers
      - ./server/src/dblogic:/app/src/dblogic
     
  vue:
    build: './frontend'
    deploy:
      replicas: 3
    restart: always
    ports:
      - 80:8080